### ISSUE TITLE
setup.py install ImportError: cannot import name RGBColor

### ISSUE THREAD

**Issue by jardaroh** [jyotiska/colorweave#1]
When attempting to install colorweave we meet this problem after resolving a few dependency issues.

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import colorweave
  File "/home/jardar/Downloads/colorweave-master/colorweave.py", line 9, in <module>
    from colormath.color_objects import RGBColor
ImportError: cannot import name RGBColor

**Comment by frakman1** [comment]
I can confirm that using version 1.0.8 fixed this issue for me on my windows box using python 2.7. The exact command I used was:

```
easy_install colormath==1.0.8
```
