### ISSUE TITLE
Pip install colorweave gives error

### ISSUE THREAD

**Issue by deronsizemore** [jyotiska/colorweave#3]
Hi,

I'm needing to extract a color palette from an image and would really like to use colorweave to compare results between it and colorific but I'm having trouble getting colorweave installed. When I run "pip install colorweave" I get this in terminal:

Downloading/unpacking colorweave
  Downloading colorweave-0.3.2.tar.gz
  Running setup.py egg_info for package colorweave
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/Deron/Sites/colorfavs/virtualenv/build/colorweave/setup.py", line 5, in <module>
        import colorweave
      File "colorweave.py", line 5, in <module>
        import webcolors
    ImportError: No module named webcolors
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/Deron/Sites/colorfavs/virtualenv/build/colorweave/setup.py", line 5, in <module>

    import colorweave

  File "colorweave.py", line 5, in <module>

    import webcolors

ImportError: No module named webcolors

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/Deron/Sites/colorfavs/virtualenv/build/colorweave

**Comment by deronsizemore** [comment]
I pip installed webcolors thinking that maybe that was it and now when I try to pip install colorweave I get this:

Downloading colorweave-0.3.2.tar.gz
  Running setup.py egg_info for package colorweave
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/Deron/Sites/colorfavs/virtualenv/build/colorweave/setup.py", line 5, in <module>
        import colorweave
      File "colorweave.py", line 9, in <module>
        from colormath.color_objects import RGBColor
    ImportError: cannot import name RGBColor
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/Deron/Sites/colorfavs/virtualenv/build/colorweave/setup.py", line 5, in <module>

    import colorweave

  File "colorweave.py", line 9, in <module>

    from colormath.color_objects import RGBColor

ImportError: cannot import name RGBColor

**Comment by deronsizemore** [comment]
Ok... sorry for all of the tickets here. It seems I needed an older version of colormath installed. When I installed 1.0.8 specifically, colorweave installs successfully

**Comment by jyotiska** [comment]
Yes, you need the 1.0.8 version of colormath for this to work correctly. Hope your issue was resolved.

**Comment by bjorntheart** [comment]
I installed the exact 1.0.8 of colormath and then installed colorweave, but get the following error 

`pip install colorweave`
        
Collecting colorweave
  Using cached colorweave-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sg/06h17kjx59g982sj0b53lmhh0000gn/T/pip-build-EUY_7l/colorweave/setup.py", line 5, in <module>
        import colorweave
      File "colorweave.py", line 5, in <module>
        import webcolors
    ImportError: No module named webcolors
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sg/06h17kjx59g982sj0b53lmhh0000gn/T/pip-build-EUY_7l/colorweave/

**Comment by jyotiska** [comment]
Can you check if you have webcolors library installed or not? If not, you can install it using pip. That should solve your issue.

**Comment by bjorntheart** [comment]
I've manually installed the following:
```
pip install 'colormath>=1.0.8'
pip install 'webcolors>=1.4'
```

Then I did a `pip install colorweave` again but get the following error:

I tried `pip install 'PIL>=1.1.6'` too, but get the following error:

```
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

I use virtualenv and my Python version is  2.7.10

**Comment by deronsizemore** [comment]
@bjorntheart I can't remember the reason, but even though I got colorweave installed I ended up finding (and using) this: https://github.com/99designs/colorific. 

It seems to work quite well. I made colorfavs.com which uses it if you'd like to see it in action.

**Comment by bjorntheart** [comment]
@deronsizemore Sweet site! thanks for the repo share also. I'll check it out immediately

**Comment by jyotiska** [comment]
Hi @bjorntheart. Thanks for trying out colorweave. Any particular reason that made you transition to colorific? As a maintainer for this package, I would definitely provide as much support as possible.

**Comment by bjorntheart** [comment]
I couldn't successfully install colorweave even with the help in this thread, so I never got around to actually playing with colorweave,  which is a bummer :-(

If I can get colorweave to work, I can evaluate it and compare it to colorific

**Comment by jyotiska** [comment]
Ok. I am currently in a process of reworking the codebase from ground up including number of dependencies it has. I will get back to you in a couple of days on this.

**Comment by deronsizemore** [comment]
> Any particular reason that made you transition to colorific? As a maintainer for this package, I would definitely provide as much support as possible.

@jyotiska I honestly can't remember why I went with Colorific over Colorweave. It's been so long since I used it. It does seem that there was something in particular that it wouldn't do (or I couldn't figure out how to do) but I could be mistaken. It might as been that I couldn't figure out how to specify a min_prominence, distance, saturation, etc. I saw them as variables in the function but didn't know if I could just pass those in as arguments?

I've actually got another project coming up where I'll need to extract colors so I'll definitely keep Colorweave in mind and give it another try.

**Comment by bjorntheart** [comment]
Great news! Look forward to it

Sent from my iPhone




On Tue, Mar 15, 2016 at 10:59 AM -0700, "Jyotiska NK" <notifications@github.com> wrote:












Ok. I am currently in a process of reworking the codebase from ground up including number of dependencies it has. I will get back to you in a couple of days on this.
